# Generated by Django 3.0.5 on 2020-04-04 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username of the user')),
                ('password', models.CharField(max_length=50, unique=True, verbose_name='password of the user')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name of the user')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('bio', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Task Title')),
                ('description', models.CharField(max_length=50, verbose_name='Task description')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time of task')),
                ('completion_time', models.DateTimeField(verbose_name='completion time')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'unpicked'), (1, 'progressing'), (2, 'completed')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.Profile')),
            ],
        ),
    ]
